using System.Text.Json.Serialization;

namespace PSImmyBot.Models;

[method: JsonConstructor]
public record Branding(
    [property: JsonPropertyName("backgroundColor")]
    string? BackgroundColor,
    [property: JsonPropertyName("createdBy")]
    int? CreatedBy,
    [property: JsonPropertyName("createdByUser")]
    User CreatedByUser,
    [property: JsonPropertyName("createdDate")]
    DateTimeOffset CreatedDate,
    [property: JsonPropertyName("description")]
    string? Description,
    [property: JsonPropertyName("endDate")]
    DateTimeOffset? EndDate,
    [property: JsonPropertyName("foregroundColor")]
    string? ForegroundColor,
    [property: JsonPropertyName("fromAddress")]
    string? FromAddress,
    [property: JsonPropertyName("id")] int Id,
    [property: JsonPropertyName("ignoreYear")]
    bool? IgnoreYear,
    [property: JsonPropertyName("logoAltText")]
    string? LogoAltText,
    [property: JsonPropertyName("logoUri")]
    string? LogoUri,
    [property: JsonPropertyName("mascotImgUri")]
    string? MascotImgUri,
    [property: JsonPropertyName("mascotName")]
    string? MascotName,
    [property: JsonPropertyName("ownerTenant")]
    Tenant OwnerTenant,
    [property: JsonPropertyName("startDate")]
    DateTimeOffset? StartDate,
    [property: JsonPropertyName("tableHeaderColor")]
    string? TableHeaderColor,
    [property: JsonPropertyName("tableHeaderTextColor")]
    string? TableHeaderTextColor,
    [property: JsonPropertyName("tenantId")]
    int? TenantId,
    [property: JsonPropertyName("textColor")]
    string? TextColor,
    [property: JsonPropertyName("timeFormat")]
    string? TimeFormat,
    [property: JsonPropertyName("updatedBy")]
    int? UpdatedBy,
    [property: JsonPropertyName("updatedByUser")]
    User UpdatedByUser,
    [property: JsonPropertyName("updatedDate")]
    DateTimeOffset UpdatedDate);
