using System.Text.Json.Serialization;

namespace PSImmyBot.Models;

[method: JsonConstructor]
public record CreateLocalSoftwareRequestBody(
    [property: JsonPropertyName("agentIntegrationTypeId")]
    Guid? AgentIntegrationTypeId,
    [property: JsonPropertyName("chocoProviderSoftwareId")]
    string? ChocoProviderSoftwareId,
    [property: JsonPropertyName("detectionMethod")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DetectionMethod>))]
    DetectionMethod DetectionMethod,
    [property: JsonPropertyName("detectionScriptId")]
    int? DetectionScriptId,
    [property: JsonPropertyName("detectionScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType DetectionScriptType,
    [property: JsonPropertyName("downloadInstallerScriptId")]
    int? DownloadInstallerScriptId,
    [property: JsonPropertyName("downloadInstallerScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType DownloadInstallerScriptType,
    [property: JsonPropertyName("dynamicVersionsScriptId")]
    int? DynamicVersionsScriptId,
    [property: JsonPropertyName("dynamicVersionsScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType DynamicVersionsScriptType,
    [property: JsonPropertyName("hidden")] bool Hidden,
    [property: JsonPropertyName("installOrder")]
    int InstallOrder,
    [property: JsonPropertyName("installScriptId")]
    int? InstallScriptId,
    [property: JsonPropertyName("installScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType InstallScriptType,
    [property: JsonPropertyName("licenseDescription")]
    string? LicenseDescription,
    [property: JsonPropertyName("licenseRequirement")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<SoftwareLicenseRequirement>))]
    SoftwareLicenseRequirement LicenseRequirement,
    [property: JsonPropertyName("licenseType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<LicenseType>))]
    LicenseType LicenseType,
    [property: JsonPropertyName("maintenanceTaskId")]
    int? MaintenanceTaskId,
    [property: JsonPropertyName("maintenanceTaskType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType MaintenanceTaskType,
    [property: JsonPropertyName("name")] string? Name,
    [property: JsonPropertyName("niniteProviderSoftwareId")]
    string? NiniteProviderSoftwareId,
    [property: JsonPropertyName("notes")] string? Notes,
    [property: JsonPropertyName("ownerTenantId")]
    int? OwnerTenantId,
    [property: JsonPropertyName("postInstallScriptId")]
    int? PostInstallScriptId,
    [property: JsonPropertyName("postInstallScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType PostInstallScriptType,
    [property: JsonPropertyName("postUninstallScriptId")]
    int? PostUninstallScriptId,
    [property: JsonPropertyName("postUninstallScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType PostUninstallScriptType,
    [property: JsonPropertyName("rebootNeeded")]
    bool RebootNeeded,
    [property: JsonPropertyName("recommended")]
    bool Recommended,
    [property: JsonPropertyName("repairScriptId")]
    int? RepairScriptId,
    [property: JsonPropertyName("repairScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType RepairScriptType,
    [property: JsonPropertyName("repairType")]
    int? RepairType,
    [property: JsonPropertyName("softwareIconMediaId")]
    int? SoftwareIconMediaId,
    [property: JsonPropertyName("softwarePrerequisites")]
    ICollection<SoftwarePrerequisite>? SoftwarePrerequisites,
    [property: JsonPropertyName("softwareTableName")]
    string? SoftwareTableName,
    [property: JsonPropertyName("softwareTableNameSearchMode")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<SoftwareTableNameSearchMode>))]
    SoftwareTableNameSearchMode SoftwareTableNameSearchMode,
    [property: JsonPropertyName("tenantSoftware")]
    ICollection<int>? TenantSoftware,
    [property: JsonPropertyName("testFailedError")]
    string? TestFailedError,
    [property: JsonPropertyName("testRequired")]
    bool TestRequired,
    [property: JsonPropertyName("testScriptId")]
    int? TestScriptId,
    [property: JsonPropertyName("testScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType TestScriptType,
    [property: JsonPropertyName("uninstallScriptId")]
    int? UninstallScriptId,
    [property: JsonPropertyName("uninstallScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType UninstallScriptType,
    [property: JsonPropertyName("upgradeCode")]
    string? UpgradeCode,
    [property: JsonPropertyName("upgradeScriptId")]
    int? UpgradeScriptId,
    [property: JsonPropertyName("upgradeScriptType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType UpgradeScriptType,
    [property: JsonPropertyName("upgradeStrategy")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<UpdateActionType>))]
    UpdateActionType UpgradeStrategy,
    [property: JsonPropertyName("useDynamicVersions")]
    bool UseDynamicVersions);
