using System.Text.Json.Serialization;

namespace PSImmyBot.Models;

[method: JsonConstructor]
public record GetMaintenanceActionResponse(
    [property: JsonPropertyName("actionType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<MaintenanceActionType>))]
    MaintenanceActionType ActionType,
    [property: JsonPropertyName("actionTypeName")]
    string? ActionTypeName,
    [property: JsonPropertyName("assignmentId")]
    int? AssignmentId,
    [property: JsonPropertyName("assignmentType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType AssignmentType,
    [property: JsonPropertyName("computerId")]
    int? ComputerId,
    [property: JsonPropertyName("computerName")]
    string? ComputerName,
    [property: JsonPropertyName("createdBy")]
    int? CreatedBy,
    [property: JsonPropertyName("createdDateUTC")]
    DateTimeOffset CreatedDateUtc,
    [property: JsonPropertyName("dependentsNames")]
    ICollection<string>? DependentsNames,
    [property: JsonPropertyName("dependsOnNames")]
    ICollection<string>? DependsOnNames,
    [property: JsonPropertyName("description")]
    string? Description,
    [property: JsonPropertyName("desiredSoftwareState")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DesiredSoftwareState>))]
    DesiredSoftwareState DesiredSoftwareState,
    [property: JsonPropertyName("desiredVersionString")]
    string? DesiredVersionString,
    [property: JsonPropertyName("detectedVersionString")]
    string? DetectedVersionString,
    [property: JsonPropertyName("endTime")]
    DateTimeOffset EndTime,
    [property: JsonPropertyName("id")] int Id,
    [property: JsonPropertyName("isComputerOnline")]
    bool IsComputerOnline,
    [property: JsonPropertyName("maintenanceDisplayName")]
    string? MaintenanceDisplayName,
    [property: JsonPropertyName("maintenanceIdentifier")]
    string? MaintenanceIdentifier,
    [property: JsonPropertyName("maintenanceSessionId")]
    int MaintenanceSessionId,
    [property: JsonPropertyName("maintenanceTaskGetResult")]
    string? MaintenanceTaskGetResult,
    [property: JsonPropertyName("maintenanceTaskMode")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<MaintenanceTaskMode>))]
    MaintenanceTaskMode MaintenanceTaskMode,
    [property: JsonPropertyName("maintenanceTaskType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType MaintenanceTaskType,
    [property: JsonPropertyName("maintenanceType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<MaintenanceType>))]
    MaintenanceType MaintenanceType,
    [property: JsonPropertyName("maintenanceTypeName")]
    string? MaintenanceTypeName,
    [property: JsonPropertyName("parentId")]
    int? ParentId,
    [property: JsonPropertyName("policyDescription")]
    string? PolicyDescription,
    [property: JsonPropertyName("postMaintenanceTest")]
    string? PostMaintenanceTest,
    [property: JsonPropertyName("postMaintenanceTestResult")]
    bool? PostMaintenanceTestResult,
    [property: JsonPropertyName("postMaintenanceTestResultMessage")]
    string? PostMaintenanceTestResultMessage,
    [property: JsonPropertyName("postMaintenanceTestType")]
    int? PostMaintenanceTestType,
    [property: JsonPropertyName("reason")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<MaintenanceActionReason>))]
    MaintenanceActionReason Reason,
    [property: JsonPropertyName("result")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<MaintenanceActionResult>))]
    MaintenanceActionResult Result,
    [property: JsonPropertyName("resultName")]
    string? ResultName,
    [property: JsonPropertyName("resultReason")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<MaintenanceActionResultReason>))]
    MaintenanceActionResultReason ResultReason,
    [property: JsonPropertyName("resultReasonMessage")]
    string? ResultReasonMessage,
    [property: JsonPropertyName("softwareActionIdForConfigurationTask")]
    int? SoftwareActionIdForConfigurationTask,
    [property: JsonPropertyName("softwareProviderType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<SoftwareProviderType>))]
    SoftwareProviderType SoftwareProviderType,
    [property: JsonPropertyName("softwareType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<SoftwareType>))]
    SoftwareType SoftwareType,
    [property: JsonPropertyName("startTime")]
    DateTimeOffset StartTime,
    [property: JsonPropertyName("status")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<MaintenanceActionStatus>))]
    MaintenanceActionStatus Status,
    [property: JsonPropertyName("statusName")]
    string? StatusName,
    [property: JsonPropertyName("tenantId")]
    int? TenantId,
    [property: JsonPropertyName("tenantName")]
    string? TenantName,
    [property: JsonPropertyName("updatedBy")]
    int? UpdatedBy,
    [property: JsonPropertyName("updatedDateUTC")]
    DateTimeOffset UpdatedDateUtc);
