using System.Text.Json.Serialization;

namespace PSImmyBot.Models;

[method: JsonConstructor]
public record GlobalSoftware(
    [property: JsonPropertyName("agentIntegrationTypeId")] Guid? AgentIntegrationTypeId,
    [property: JsonPropertyName("chocoProviderSoftwareId")] string? ChocoProviderSoftwareId,
    [property: JsonPropertyName("createdBy")] int? CreatedBy,
    [property: JsonPropertyName("createdDate")] DateTimeOffset CreatedDate,
    [property: JsonPropertyName("customAuditProperties")] ICollection<AuditPropertyChange>? CustomAuditProperties,
    [property: JsonPropertyName("detectionMethod")][property: JsonConverter(typeof(JsonStringEnumConverter<DetectionMethod>))] DetectionMethod DetectionMethod,
    [property: JsonPropertyName("detectionScript")] Script DetectionScript,
    [property: JsonPropertyName("detectionScriptId")] int? DetectionScriptId,
    [property: JsonPropertyName("detectionScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType DetectionScriptType,
    [property: JsonPropertyName("downloadInstallerScript")] Script DownloadInstallerScript,
    [property: JsonPropertyName("downloadInstallerScriptId")] int? DownloadInstallerScriptId,
    [property: JsonPropertyName("downloadInstallerScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType DownloadInstallerScriptType,
    [property: JsonPropertyName("dynamicVersionsScript")] Script DynamicVersionsScript,
    [property: JsonPropertyName("dynamicVersionsScriptId")] int? DynamicVersionsScriptId,
    [property: JsonPropertyName("dynamicVersionsScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType DynamicVersionsScriptType,
    [property: JsonPropertyName("hidden")] bool Hidden,
    [property: JsonPropertyName("id")] int Id,
    [property: JsonPropertyName("identifier")] string? Identifier,
    [property: JsonPropertyName("installOrder")] int InstallOrder,
    [property: JsonPropertyName("installScript")] Script InstallScript,
    [property: JsonPropertyName("installScriptId")] int? InstallScriptId,
    [property: JsonPropertyName("installScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType InstallScriptType,
    [property: JsonPropertyName("licenseDescription")] string? LicenseDescription,
    [property: JsonPropertyName("licenseRequirement")][property: JsonConverter(typeof(JsonStringEnumConverter<SoftwareLicenseRequirement>))] SoftwareLicenseRequirement LicenseRequirement,
    [property: JsonPropertyName("licenseType")][property: JsonConverter(typeof(JsonStringEnumConverter<LicenseType>))] LicenseType LicenseType,
    [property: JsonPropertyName("maintenanceSpecifier")] MaintenanceSpecifier MaintenanceSpecifier,
    [property: JsonPropertyName("maintenanceTask")] MaintenanceTask MaintenanceTask,
    [property: JsonPropertyName("maintenanceTaskId")] int? MaintenanceTaskId,
    [property: JsonPropertyName("maintenanceTaskType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType MaintenanceTaskType,
    [property: JsonPropertyName("maintenanceType")][property: JsonConverter(typeof(JsonStringEnumConverter<MaintenanceType>))] MaintenanceType MaintenanceType,
    [property: JsonPropertyName("name")] string? Name,
    [property: JsonPropertyName("niniteProviderSoftwareId")] string? NiniteProviderSoftwareId,
    [property: JsonPropertyName("notes")] string? Notes,
    [property: JsonPropertyName("postInstallScript")] Script PostInstallScript,
    [property: JsonPropertyName("postInstallScriptId")] int? PostInstallScriptId,
    [property: JsonPropertyName("postInstallScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType PostInstallScriptType,
    [property: JsonPropertyName("postUninstallScript")] Script PostUninstallScript,
    [property: JsonPropertyName("postUninstallScriptId")] int? PostUninstallScriptId,
    [property: JsonPropertyName("postUninstallScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType PostUninstallScriptType,
    [property: JsonPropertyName("rebootNeeded")] bool RebootNeeded,
    [property: JsonPropertyName("recommended")] bool Recommended,
    [property: JsonPropertyName("relativeCacheSourcePath")] Guid RelativeCacheSourcePath,
    [property: JsonPropertyName("repairScript")] Script RepairScript,
    [property: JsonPropertyName("repairScriptId")] int? RepairScriptId,
    [property: JsonPropertyName("repairScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType RepairScriptType,
    [property: JsonPropertyName("repairType")][property: JsonConverter(typeof(JsonStringEnumConverter<RepairActionType>))] RepairActionType RepairType,
    [property: JsonPropertyName("softwareIcon")] Media SoftwareIcon,
    [property: JsonPropertyName("softwareIconMediaId")] int? SoftwareIconMediaId,
    [property: JsonPropertyName("softwarePrerequisites")] ICollection<SoftwarePrerequisite>? SoftwarePrerequisites,
    [property: JsonPropertyName("softwareTableName")] string? SoftwareTableName,
    [property: JsonPropertyName("softwareTableNameSearchMode")][property: JsonConverter(typeof(JsonStringEnumConverter<SoftwareTableNameSearchMode>))] SoftwareTableNameSearchMode SoftwareTableNameSearchMode,
    [property: JsonPropertyName("softwareType")][property: JsonConverter(typeof(JsonStringEnumConverter<SoftwareType>))] SoftwareType SoftwareType,
    [property: JsonPropertyName("softwareVersions")] ICollection<GlobalSoftwareVersion>? SoftwareVersions,
    [property: JsonPropertyName("testFailedError")] string? TestFailedError,
    [property: JsonPropertyName("testRequired")] bool TestRequired,
    [property: JsonPropertyName("testScript")] Script TestScript,
    [property: JsonPropertyName("testScriptId")] int? TestScriptId,
    [property: JsonPropertyName("testScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType TestScriptType,
    [property: JsonPropertyName("uninstallScript")] Script UninstallScript,
    [property: JsonPropertyName("uninstallScriptId")] int? UninstallScriptId,
    [property: JsonPropertyName("uninstallScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType UninstallScriptType,
    [property: JsonPropertyName("updatedBy")] int? UpdatedBy,
    [property: JsonPropertyName("updatedDate")] DateTimeOffset UpdatedDate,
    [property: JsonPropertyName("upgradeCode")] string? UpgradeCode,
    [property: JsonPropertyName("upgradeScript")] Script UpgradeScript,
    [property: JsonPropertyName("upgradeScriptId")] int? UpgradeScriptId,
    [property: JsonPropertyName("upgradeScriptType")][property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))] DatabaseType UpgradeScriptType,
    [property: JsonPropertyName("upgradeStrategy")][property: JsonConverter(typeof(JsonStringEnumConverter<UpdateActionType>))] UpdateActionType UpgradeStrategy,
    [property: JsonPropertyName("useDynamicVersions")] bool UseDynamicVersions,
    [property: JsonPropertyName("useSoftwareTableDetection")][property: Obsolete] bool UseSoftwareTableDetection
);
