using System.Text.Json.Serialization;

namespace PSImmyBot.Models;

[method: JsonConstructor]
public record RunImmyServiceRequestBody(
    [property: JsonPropertyName("allowAccessToParentTenant")]
    bool AllowAccessToParentTenant,
    [property: JsonPropertyName("autoConsentToReboots")]
    bool AutoConsentToReboots,
    [property: JsonPropertyName("cacheOnly")]
    bool CacheOnly,
    [property: JsonPropertyName("computers")]
    ICollection<RunImmybotComputerRequestBody>? Computers,
    [property: JsonPropertyName("deploymentId")]
    int? DeploymentId,
    [property: JsonPropertyName("deploymentType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType DeploymentType,
    [property: JsonPropertyName("detectionOnly")]
    bool DetectionOnly,
    [property: JsonPropertyName("fullMaintenance")]
    bool FullMaintenance,
    [property: JsonPropertyName("inventoryOnly")]
    bool InventoryOnly,
    [property: JsonPropertyName("licenseId")]
    int? LicenseId,
    [property: JsonPropertyName("maintenanceParams")]
    RunImmybotMaintenanceRequestBody MaintenanceParams,
    [property: JsonPropertyName("offlineBehavior")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<ComputerOfflineMaintenanceSessionBehavior>))]
    ComputerOfflineMaintenanceSessionBehavior OfflineBehavior,
    [property: JsonPropertyName("persons")]
    ICollection<RunImmybotPersonRequestBody>? Persons,
    [property: JsonPropertyName("promptTimeoutAction")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<PromptTimeoutAction>))]
    PromptTimeoutAction PromptTimeoutAction,
    [property: JsonPropertyName("promptTimeoutMinutes")]
    int PromptTimeoutMinutes,
    [property: JsonPropertyName("propagateToChildTenants")]
    bool PropagateToChildTenants,
    [property: JsonPropertyName("providerLinkIdForAgentUpdates")]
    int? ProviderLinkIdForAgentUpdates,
    [property: JsonPropertyName("rebootPreference")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<RebootPreference>))]
    RebootPreference RebootPreference,
    [property: JsonPropertyName("resolutionOnly")]
    bool ResolutionOnly,
    [property: JsonPropertyName("runInventoryInDetection")]
    bool RunInventoryInDetection,
    [property: JsonPropertyName("scheduleExecutionAfterActiveHours")]
    bool ScheduleExecutionAfterActiveHours,
    [property: JsonPropertyName("sendDetectionEmail")]
    bool SendDetectionEmail,
    [property: JsonPropertyName("sendDetectionEmailWhenAllActionsAreCompliant")]
    bool SendDetectionEmailWhenAllActionsAreCompliant,
    [property: JsonPropertyName("sendFollowUpEmail")]
    bool SendFollowUpEmail,
    [property: JsonPropertyName("sendFollowUpOnlyIfActionNeeded")]
    bool SendFollowUpOnlyIfActionNeeded,
    [property: JsonPropertyName("sessionGroupId")]
    Guid? SessionGroupId,
    [property: JsonPropertyName("showMaintenanceActions")]
    bool ShowMaintenanceActions,
    [property: JsonPropertyName("showPostponeButton")]
    bool ShowPostponeButton,
    [property: JsonPropertyName("showRunNowButton")]
    bool ShowRunNowButton,
    [property: JsonPropertyName("skipBackgroundJob")]
    bool SkipBackgroundJob,
    [property: JsonPropertyName("suppressRebootsDuringBusinessHours")]
    bool SuppressRebootsDuringBusinessHours,
    [property: JsonPropertyName("tenants")]
    ICollection<RunImmybotTenantRequestBody>? Tenants,
    [property: JsonPropertyName("timeZoneInfoId")]
    string? TimeZoneInfoId,
    [property: JsonPropertyName("updateTime")]
    string? UpdateTime,
    [property: JsonPropertyName("useComputersTimezoneForExecution")]
    bool UseComputersTimezoneForExecution,
    [property: JsonPropertyName("useWinningDeployment")]
    bool UseWinningDeployment);
