using System.Text.Json.Serialization;

namespace PSImmyBot.Models;

[method: JsonConstructor]
public record SessionJobArgs(
    [property: JsonPropertyName("actionIdToRerun")]
    int? ActionIdToRerun,
    [property: JsonPropertyName("allowAccessToParentTenant")]
    bool AllowAccessToParentTenant,
    [property: JsonPropertyName("appliedOnConnect")]
    bool AppliedOnConnect,
    [property: JsonPropertyName("autoConsentToReboots")]
    bool AutoConsentToReboots,
    [property: JsonPropertyName("cacheGroupId")]
    Guid? CacheGroupId,
    [property: JsonPropertyName("cacheOnly")]
    bool CacheOnly,
    [property: JsonPropertyName("computerId")]
    int? ComputerId,
    [property: JsonPropertyName("deploymentId")]
    int? DeploymentId,
    [property: JsonPropertyName("deploymentType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<DatabaseType>))]
    DatabaseType DeploymentType,
    [property: JsonPropertyName("detectionOnly")]
    bool DetectionOnly,
    [property: JsonPropertyName("enqueuedSessionType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<EnqueuedSessionType>))]
    EnqueuedSessionType EnqueuedSessionType,
    [property: JsonPropertyName("hasSessionFeatureBeenTracked")]
    bool HasSessionFeatureBeenTracked,
    [property: JsonPropertyName("installWindowsUpdates")]
    bool InstallWindowsUpdates,
    [property: JsonPropertyName("inventoryOnly")]
    bool InventoryOnly,
    [property: JsonPropertyName("maintenanceAgentUpdatesConfiguration")]
    MaintenanceAgentUpdatesConfiguration MaintenanceAgentUpdatesConfiguration,
    [property: JsonPropertyName("maintenanceEmailConfiguration")]
    MaintenanceEmailConfiguration MaintenanceEmailConfiguration,
    [property: JsonPropertyName("maintenanceItem")]
    MaintenanceItem MaintenanceItem,
    [property: JsonPropertyName("maintenanceOnboardingConfiguration")]
    MaintenanceOnboardingConfiguration MaintenanceOnboardingConfiguration,
    [property: JsonPropertyName("maintenanceSchedulingConfiguration")]
    MaintenanceSchedulingConfiguration MaintenanceSchedulingConfiguration,
    [property: JsonPropertyName("manuallyResumed")]
    bool ManuallyResumed,
    [property: JsonPropertyName("manuallyResumedByPersonId")]
    int? ManuallyResumedByPersonId,
    [property: JsonPropertyName("manuallyTriggeredByUserId")]
    int? ManuallyTriggeredByUserId,
    [property: JsonPropertyName("offlineBehavior")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<ComputerOfflineMaintenanceSessionBehavior>))]
    ComputerOfflineMaintenanceSessionBehavior OfflineBehavior,
    [property: JsonPropertyName("personId")]
    int? PersonId,
    [property: JsonPropertyName("promptTimeoutAction")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<PromptTimeoutAction>))]
    PromptTimeoutAction PromptTimeoutAction,
    [property: JsonPropertyName("promptTimeoutMinutes")]
    int PromptTimeoutMinutes,
    [property: JsonPropertyName("propagateToChildTenants")]
    bool PropagateToChildTenants,
    [property: JsonPropertyName("rebootPreference")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<RebootPreference>))]
    RebootPreference RebootPreference,
    [property: JsonPropertyName("repair")] bool Repair,
    [property: JsonPropertyName("rerunFromScheduleId")]
    int? RerunFromScheduleId,
    [property: JsonPropertyName("rerunningAction")]
    bool RerunningAction,
    [property: JsonPropertyName("resolutionOnly")]
    bool ResolutionOnly,
    [property: JsonPropertyName("runInventoryInDetection")]
    bool RunInventoryInDetection,
    [property: JsonPropertyName("scheduledId")]
    int? ScheduledId,
    [property: JsonPropertyName("sessionGroupId")]
    Guid? SessionGroupId,
    [property: JsonPropertyName("suppressRebootsDuringBusinessHours")]
    bool SuppressRebootsDuringBusinessHours,
    [property: JsonPropertyName("tenantId")]
    int? TenantId,
    [property: JsonPropertyName("terminalId")]
    Guid? TerminalId,
    [property: JsonPropertyName("useWinningDeployment")]
    bool UseWinningDeployment);
