using System.Text.Json.Serialization;

namespace PSImmyBot.Models;

[method: JsonConstructor]
public record UpdateGlobalSoftwareVersionRequestBody(
    [property: JsonPropertyName("blobName")]
    string? BlobName,
    [property: JsonPropertyName("currentSemanticVersion")]
    SemanticVersion CurrentSemanticVersion,
    [property: JsonPropertyName("dependsOnSemanticVersion")]
    SemanticVersion DependsOnSemanticVersion,
    [property: JsonPropertyName("displayName")]
    string? DisplayName,
    [property: JsonPropertyName("displayVersion")]
    string? DisplayVersion,
    [property: JsonPropertyName("installerFile")]
    string? InstallerFile,
    [property: JsonPropertyName("installerType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<SoftwareVersionInstallerType>))]
    SoftwareVersionInstallerType InstallerType,
    [property: JsonPropertyName("installScriptId")]
    int? InstallScriptId,
    [property: JsonPropertyName("licenseType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<LicenseType>))]
    LicenseType LicenseType,
    [property: JsonPropertyName("notes")] string? Notes,
    [property: JsonPropertyName("packageHash")]
    string? PackageHash,
    [property: JsonPropertyName("packageType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<PackageType>))]
    PackageType PackageType,
    [property: JsonPropertyName("postInstallScriptId")]
    int? PostInstallScriptId,
    [property: JsonPropertyName("postUninstallScriptId")]
    int? PostUninstallScriptId,
    [property: JsonPropertyName("productCode")]
    string? ProductCode,
    [property: JsonPropertyName("relativeCacheSourcePath")]
    string? RelativeCacheSourcePath,
    [property: JsonPropertyName("semanticVersion")]
    [property: System.ComponentModel.DataAnnotations.Required]
    SemanticVersion SemanticVersion,
    [property: JsonPropertyName("softwareId")]
    int SoftwareId,
    [property: JsonPropertyName("softwareIdentifier")]
    string? SoftwareIdentifier,
    [property: JsonPropertyName("softwareType")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<SoftwareType>))]
    SoftwareType SoftwareType,
    [property: JsonPropertyName("testFailedError")]
    string? TestFailedError,
    [property: JsonPropertyName("testRequired")]
    bool TestRequired,
    [property: JsonPropertyName("testScriptId")]
    int? TestScriptId,
    [property: JsonPropertyName("uninstallScriptId")]
    int? UninstallScriptId,
    [property: JsonPropertyName("upgradeScriptId")]
    int? UpgradeScriptId,
    [property: JsonPropertyName("upgradeStrategy")]
    [property: JsonConverter(typeof(JsonStringEnumConverter<UpdateActionType>))]
    UpdateActionType UpgradeStrategy,
    [property: JsonPropertyName("url")] string? Url);
