using System.Text.Json.Serialization;

namespace PSImmyBot.Models;

[method: JsonConstructor]
public record User(
    [property: JsonPropertyName("accessFailedCount")]
    int AccessFailedCount,
    [property: JsonPropertyName("accessRequestAcknowledgements")]
    ICollection<AccessRequest>? AccessRequestAcknowledgements,
    [property: JsonPropertyName("azurePrincipalId")]
    string? AzurePrincipalId,
    [property: JsonPropertyName("canManageCrossTenantDeployments")]
    bool CanManageCrossTenantDeployments,
    [property: JsonPropertyName("concurrencyStamp")]
    string? ConcurrencyStamp,
    [property: JsonPropertyName("createdBrandings")]
    ICollection<Branding>? CreatedBrandings,
    [property: JsonPropertyName("createdBy")]
    int? CreatedBy,
    [property: JsonPropertyName("createdChangeRequestComments")]
    ICollection<ChangeRequestComment>? CreatedChangeRequestComments,
    [property: JsonPropertyName("createdChangeRequests")]
    ICollection<ChangeRequest>? CreatedChangeRequests,
    [property: JsonPropertyName("createdDate")]
    DateTimeOffset CreatedDate,
    [property: JsonPropertyName("createdDeployments")]
    ICollection<TargetAssignment>? CreatedDeployments,
    [property: JsonPropertyName("createdLicenses")]
    ICollection<License>? CreatedLicenses,
    [property: JsonPropertyName("createdMaintenanceSessions")]
    ICollection<MaintenanceSession>? CreatedMaintenanceSessions,
    [property: JsonPropertyName("createdMaintenanceTasks")]
    ICollection<MaintenanceTask>? CreatedMaintenanceTasks,
    [property: JsonPropertyName("createdMedia")]
    ICollection<Media>? CreatedMedia,
    [property: JsonPropertyName("createdPersons")]
    ICollection<Person>? CreatedPersons,
    [property: JsonPropertyName("createdProviderLinks")]
    ICollection<ProviderLink>? CreatedProviderLinks,
    [property: JsonPropertyName("createdRecommendedTargetAssignmentApprovals")]
    ICollection<RecommendedTargetAssignmentApproval>? CreatedRecommendedTargetAssignmentApprovals,
    [property: JsonPropertyName("createdSchedules")]
    ICollection<Schedule>? CreatedSchedules,
    [property: JsonPropertyName("createdScripts")]
    ICollection<Script>? CreatedScripts,
    [property: JsonPropertyName("createdSoftware")]
    ICollection<LocalSoftware>? CreatedSoftware,
    [property: JsonPropertyName("createdSoftwareVersions")]
    ICollection<LocalSoftwareVersion>? CreatedSoftwareVersions,
    [property: JsonPropertyName("createdTags")]
    ICollection<Tag>? CreatedTags,
    [property: JsonPropertyName("customAuditProperties")]
    ICollection<AuditPropertyChange>? CustomAuditProperties,
    [property: JsonPropertyName("displayName")]
    string? DisplayName,
    [property: JsonPropertyName("email")] string? Email,
    [property: JsonPropertyName("emailConfirmed")]
    bool EmailConfirmed,
    [property: JsonPropertyName("expirationDateUTC")]
    DateTimeOffset? ExpirationDateUtc,
    [property: JsonPropertyName("hasManagementAccess")]
    bool HasManagementAccess,
    [property: JsonPropertyName("id")] int Id,
    [property: JsonPropertyName("impersonatedByUsers")]
    ICollection<UserImpersonation>? ImpersonatedByUsers,
    [property: JsonPropertyName("impersonatorUser")]
    User ImpersonatorUser,
    [property: JsonPropertyName("isAdmin")]
    bool IsAdmin,
    [property: JsonPropertyName("isSupportTechnician")]
    bool IsSupportTechnician,
    [property: JsonPropertyName("lockoutEnabled")]
    bool LockoutEnabled,
    [property: JsonPropertyName("lockoutEnd")]
    DateTimeOffset? LockoutEnd,
    [property: JsonPropertyName("normalizedEmail")]
    string? NormalizedEmail,
    [property: JsonPropertyName("normalizedUserName")]
    string? NormalizedUserName,
    [property: JsonPropertyName("ownerTenant")]
    Tenant OwnerTenant,
    [property: JsonPropertyName("passwordHash")]
    string? PasswordHash,
    [property: JsonPropertyName("person")] Person Person,
    [property: JsonPropertyName("personId")]
    int? PersonId,
    [property: JsonPropertyName("phoneNumber")]
    string? PhoneNumber,
    [property: JsonPropertyName("phoneNumberConfirmed")]
    bool PhoneNumberConfirmed,
    [property: JsonPropertyName("securityStamp")]
    string? SecurityStamp,
    [property: JsonPropertyName("servicePrincipalId")]
    string? ServicePrincipalId,
    [property: JsonPropertyName("silencedNotifications")]
    ICollection<UserSilencedNotification>? SilencedNotifications,
    [property: JsonPropertyName("tenantId")]
    int TenantId,
    [property: JsonPropertyName("twoFactorEnabled")]
    bool TwoFactorEnabled,
    [property: JsonPropertyName("updatedBrandings")]
    ICollection<Branding>? UpdatedBrandings,
    [property: JsonPropertyName("updatedBy")]
    int? UpdatedBy,
    [property: JsonPropertyName("updatedChangeRequestComments")]
    ICollection<ChangeRequestComment>? UpdatedChangeRequestComments,
    [property: JsonPropertyName("updatedChangeRequests")]
    ICollection<ChangeRequest>? UpdatedChangeRequests,
    [property: JsonPropertyName("updatedDate")]
    DateTimeOffset UpdatedDate,
    [property: JsonPropertyName("updatedDeployments")]
    ICollection<TargetAssignment>? UpdatedDeployments,
    [property: JsonPropertyName("updatedLicenses")]
    ICollection<License>? UpdatedLicenses,
    [property: JsonPropertyName("updatedMaintenanceTasks")]
    ICollection<MaintenanceTask>? UpdatedMaintenanceTasks,
    [property: JsonPropertyName("updatedMedia")]
    ICollection<Media>? UpdatedMedia,
    [property: JsonPropertyName("updatedPersons")]
    ICollection<Person>? UpdatedPersons,
    [property: JsonPropertyName("updatedProviderLinks")]
    ICollection<ProviderLink>? UpdatedProviderLinks,
    [property: JsonPropertyName("updatedRecommendedTargetAssignmentApprovals")]
    ICollection<RecommendedTargetAssignmentApproval>? UpdatedRecommendedTargetAssignmentApprovals,
    [property: JsonPropertyName("updatedSchedules")]
    ICollection<Schedule>? UpdatedSchedules,
    [property: JsonPropertyName("updatedScripts")]
    ICollection<Script>? UpdatedScripts,
    [property: JsonPropertyName("updatedSoftware")]
    ICollection<LocalSoftware>? UpdatedSoftware,
    [property: JsonPropertyName("updatedSoftwareVersions")]
    ICollection<LocalSoftwareVersion>? UpdatedSoftwareVersions,
    [property: JsonPropertyName("updatedTags")]
    ICollection<Tag>? UpdatedTags,
    [property: JsonPropertyName("userImpersonations")]
    ICollection<UserImpersonation>? UserImpersonations,
    [property: JsonPropertyName("userName")]
    string? UserName,
    [property: JsonPropertyName("userRoles")]
    ICollection<UserRole>? UserRoles);
